Repository cloudposse/terraform-aws-transit-gateway, pull requests merged in 2024-03, with the labels that each got.

#26 Updating default value description to match actual default value
  README.md
  docs/terraform.md
  variables.tf
Labels: documentation, patch, readme

#39 Update Scaffolding
  .github/mergify.yml
  README.md
  README.yaml
Labels: auto-update, no-release, do not merge, migration

#40 Configurable timeoutes
  README.md
  docs/terraform.md
  main.tf
  modules/subnet_route/main.tf
  modules/subnet_route/variables.tf
  variables.tf
Labels: triage, needs-test
